// Generated by CoffeeScript 1.7.1
(function() {
  (function($) {
    return $.fn.customUploadButton = function(settings) {
      var options;
      options = $.extend({
        placeholder: "Nenhum arquivo selecionado",
        name: 'fileupload'
      }, settings);
      return this.each(function() {
        var button, fileInput, op;
        button = $(this);
        button.data(options).addClass('file-button').css({
          position: 'relative',
          overflow: 'hidden'
        });
        op = button.data();
        fileInput = $("<input>").attr({
          "class": "input-file",
          type: "file",
          name: op.name
        }).css({
          position: 'absolute',
          opacity: 0,
          cursor: 'pointer'
        });
        return button.bind("mousemove", function(e) {
          var fileUpload;
          fileUpload = $(this).find('.input-file');
          return fileUpload.css({
            left: e.pageX - $(this).offset().left - fileUpload.width() + 10,
            top: e.pageY - $(this).offset().top - 11
          });
        }).append(fileInput);
      });
    };
  })(jQuery);

}).call(this);
