// Generated by CoffeeScript 1.7.1
(function() {
  (function($) {
    return $.fn.customUploadButton = function(settings) {
      var options;
      options = $.extend({
        placeholder: "Nenhum arquivo selecionado"
      }, settings);
      return this.each(function() {
        var container, fileName, input, inputButton, op, pl, pr;
        container = $("<div>").attr("class", "input-wrapper");
        fileName = $("<div>").attr("class", "file-name").text(options.placeholder);
        inputButton = $("<input>").attr("class", "input-button").attr("type", "button").val("Upload");
        input = $(this);
        input.data(options).addClass('file-upload');
        op = input.data();
        container.insertAfter(input).append(fileName).append(inputButton).append(input);
        pl = parseInt(container.css("paddingLeft"));
        pr = parseInt(container.css("paddingRight"));
        fileName.css({
          width: op.width - pl - pr - inputButton.width(),
          height: op.height,
          overflow: "hidden"
        });
        input.change(function() {
          return $(this).prev(".file-name").text($(this).val() === '' ? $(this).data('placeholder') : $(this).val());
        });
        return container.bind("mousemove", function(e) {
          var fileUpload;
          fileUpload = $(this).find('.file-upload');
          return fileUpload.css({
            left: e.pageX - $(this).position().left - fileUpload.width() + 10,
            top: e.pageY - $(this).position().top - 30
          });
        });
      });
    };
  })(jQuery);

}).call(this);
